#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PO5_SERVICE
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Database1")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertInvoice(Invoice instance);
    partial void UpdateInvoice(Invoice instance);
    partial void DeleteInvoice(Invoice instance);
    partial void InsertProduct(Product instance);
    partial void UpdateProduct(Product instance);
    partial void DeleteProduct(Product instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertSHOPPING_CART(SHOPPING_CART instance);
    partial void UpdateSHOPPING_CART(SHOPPING_CART instance);
    partial void DeleteSHOPPING_CART(SHOPPING_CART instance);
    partial void InsertPurchaseInfo(PurchaseInfo instance);
    partial void UpdatePurchaseInfo(PurchaseInfo instance);
    partial void DeletePurchaseInfo(PurchaseInfo instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Database1ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Invoice> Invoices
		{
			get
			{
				return this.GetTable<Invoice>();
			}
		}
		
		public System.Data.Linq.Table<Product> Products
		{
			get
			{
				return this.GetTable<Product>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<SHOPPING_CART> SHOPPING_CARTs
		{
			get
			{
				return this.GetTable<SHOPPING_CART>();
			}
		}
		
		public System.Data.Linq.Table<PurchaseInfo> PurchaseInfos
		{
			get
			{
				return this.GetTable<PurchaseInfo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Invoice")]
	public partial class Invoice : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _User_Id;
		
		private int _Order_ID;
		
		private int _Status;
		
		private string _PointsUsed;
		
		private string _Total;
		
		private string _DiscountRecieved;
		
		private System.DateTime _InvoiceDate;
		
		private System.DateTime _DueDate;
		
		private string _VAT;
		
		private string _Adressline_1;
		
		private string _Adressline_2;
		
		private string _Adressline_3;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUser_IdChanging(int value);
    partial void OnUser_IdChanged();
    partial void OnOrder_IDChanging(int value);
    partial void OnOrder_IDChanged();
    partial void OnStatusChanging(int value);
    partial void OnStatusChanged();
    partial void OnPointsUsedChanging(string value);
    partial void OnPointsUsedChanged();
    partial void OnTotalChanging(string value);
    partial void OnTotalChanged();
    partial void OnDiscountRecievedChanging(string value);
    partial void OnDiscountRecievedChanged();
    partial void OnInvoiceDateChanging(System.DateTime value);
    partial void OnInvoiceDateChanged();
    partial void OnDueDateChanging(System.DateTime value);
    partial void OnDueDateChanged();
    partial void OnVATChanging(string value);
    partial void OnVATChanged();
    partial void OnAdressline_1Changing(string value);
    partial void OnAdressline_1Changed();
    partial void OnAdressline_2Changing(string value);
    partial void OnAdressline_2Changed();
    partial void OnAdressline_3Changing(string value);
    partial void OnAdressline_3Changed();
    #endregion
		
		public Invoice()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Id", DbType="Int NOT NULL")]
		public int User_Id
		{
			get
			{
				return this._User_Id;
			}
			set
			{
				if ((this._User_Id != value))
				{
					this.OnUser_IdChanging(value);
					this.SendPropertyChanging();
					this._User_Id = value;
					this.SendPropertyChanged("User_Id");
					this.OnUser_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Order_ID", DbType="Int NOT NULL")]
		public int Order_ID
		{
			get
			{
				return this._Order_ID;
			}
			set
			{
				if ((this._Order_ID != value))
				{
					this.OnOrder_IDChanging(value);
					this.SendPropertyChanging();
					this._Order_ID = value;
					this.SendPropertyChanged("Order_ID");
					this.OnOrder_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int NOT NULL")]
		public int Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PointsUsed", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PointsUsed
		{
			get
			{
				return this._PointsUsed;
			}
			set
			{
				if ((this._PointsUsed != value))
				{
					this.OnPointsUsedChanging(value);
					this.SendPropertyChanging();
					this._PointsUsed = value;
					this.SendPropertyChanged("PointsUsed");
					this.OnPointsUsedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this.OnTotalChanging(value);
					this.SendPropertyChanging();
					this._Total = value;
					this.SendPropertyChanged("Total");
					this.OnTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiscountRecieved", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DiscountRecieved
		{
			get
			{
				return this._DiscountRecieved;
			}
			set
			{
				if ((this._DiscountRecieved != value))
				{
					this.OnDiscountRecievedChanging(value);
					this.SendPropertyChanging();
					this._DiscountRecieved = value;
					this.SendPropertyChanged("DiscountRecieved");
					this.OnDiscountRecievedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceDate", DbType="Date NOT NULL")]
		public System.DateTime InvoiceDate
		{
			get
			{
				return this._InvoiceDate;
			}
			set
			{
				if ((this._InvoiceDate != value))
				{
					this.OnInvoiceDateChanging(value);
					this.SendPropertyChanging();
					this._InvoiceDate = value;
					this.SendPropertyChanged("InvoiceDate");
					this.OnInvoiceDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DueDate", DbType="Date NOT NULL")]
		public System.DateTime DueDate
		{
			get
			{
				return this._DueDate;
			}
			set
			{
				if ((this._DueDate != value))
				{
					this.OnDueDateChanging(value);
					this.SendPropertyChanging();
					this._DueDate = value;
					this.SendPropertyChanged("DueDate");
					this.OnDueDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VAT", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string VAT
		{
			get
			{
				return this._VAT;
			}
			set
			{
				if ((this._VAT != value))
				{
					this.OnVATChanging(value);
					this.SendPropertyChanging();
					this._VAT = value;
					this.SendPropertyChanged("VAT");
					this.OnVATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adressline_1", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Adressline_1
		{
			get
			{
				return this._Adressline_1;
			}
			set
			{
				if ((this._Adressline_1 != value))
				{
					this.OnAdressline_1Changing(value);
					this.SendPropertyChanging();
					this._Adressline_1 = value;
					this.SendPropertyChanged("Adressline_1");
					this.OnAdressline_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adressline_2", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Adressline_2
		{
			get
			{
				return this._Adressline_2;
			}
			set
			{
				if ((this._Adressline_2 != value))
				{
					this.OnAdressline_2Changing(value);
					this.SendPropertyChanging();
					this._Adressline_2 = value;
					this.SendPropertyChanged("Adressline_2");
					this.OnAdressline_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adressline_3", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Adressline_3
		{
			get
			{
				return this._Adressline_3;
			}
			set
			{
				if ((this._Adressline_3 != value))
				{
					this.OnAdressline_3Changing(value);
					this.SendPropertyChanging();
					this._Adressline_3 = value;
					this.SendPropertyChanged("Adressline_3");
					this.OnAdressline_3Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Product")]
	public partial class Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _P_name;
		
		private string _P_publisher;
		
		private string _P_price;
		
		private string _P_description_;
		
		private string _P_Img;
		
		private int _P_Quantity;
		
		private System.DateTime _P_PublishedDate;
		
		private string _P_AuthorName;
		
		private string _P_category;
		
		private string _P_Language;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnP_nameChanging(string value);
    partial void OnP_nameChanged();
    partial void OnP_publisherChanging(string value);
    partial void OnP_publisherChanged();
    partial void OnP_priceChanging(string value);
    partial void OnP_priceChanged();
    partial void OnP_description_Changing(string value);
    partial void OnP_description_Changed();
    partial void OnP_ImgChanging(string value);
    partial void OnP_ImgChanged();
    partial void OnP_QuantityChanging(int value);
    partial void OnP_QuantityChanged();
    partial void OnP_PublishedDateChanging(System.DateTime value);
    partial void OnP_PublishedDateChanged();
    partial void OnP_AuthorNameChanging(string value);
    partial void OnP_AuthorNameChanged();
    partial void OnP_categoryChanging(string value);
    partial void OnP_categoryChanged();
    partial void OnP_LanguageChanging(string value);
    partial void OnP_LanguageChanged();
    #endregion
		
		public Product()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string P_name
		{
			get
			{
				return this._P_name;
			}
			set
			{
				if ((this._P_name != value))
				{
					this.OnP_nameChanging(value);
					this.SendPropertyChanging();
					this._P_name = value;
					this.SendPropertyChanged("P_name");
					this.OnP_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_publisher", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string P_publisher
		{
			get
			{
				return this._P_publisher;
			}
			set
			{
				if ((this._P_publisher != value))
				{
					this.OnP_publisherChanging(value);
					this.SendPropertyChanging();
					this._P_publisher = value;
					this.SendPropertyChanged("P_publisher");
					this.OnP_publisherChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_price", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string P_price
		{
			get
			{
				return this._P_price;
			}
			set
			{
				if ((this._P_price != value))
				{
					this.OnP_priceChanging(value);
					this.SendPropertyChanging();
					this._P_price = value;
					this.SendPropertyChanged("P_price");
					this.OnP_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[P_description ]", Storage="_P_description_", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string P_description_
		{
			get
			{
				return this._P_description_;
			}
			set
			{
				if ((this._P_description_ != value))
				{
					this.OnP_description_Changing(value);
					this.SendPropertyChanging();
					this._P_description_ = value;
					this.SendPropertyChanged("P_description_");
					this.OnP_description_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Img", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string P_Img
		{
			get
			{
				return this._P_Img;
			}
			set
			{
				if ((this._P_Img != value))
				{
					this.OnP_ImgChanging(value);
					this.SendPropertyChanging();
					this._P_Img = value;
					this.SendPropertyChanged("P_Img");
					this.OnP_ImgChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Quantity", DbType="Int NOT NULL")]
		public int P_Quantity
		{
			get
			{
				return this._P_Quantity;
			}
			set
			{
				if ((this._P_Quantity != value))
				{
					this.OnP_QuantityChanging(value);
					this.SendPropertyChanging();
					this._P_Quantity = value;
					this.SendPropertyChanged("P_Quantity");
					this.OnP_QuantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_PublishedDate", DbType="Date NOT NULL")]
		public System.DateTime P_PublishedDate
		{
			get
			{
				return this._P_PublishedDate;
			}
			set
			{
				if ((this._P_PublishedDate != value))
				{
					this.OnP_PublishedDateChanging(value);
					this.SendPropertyChanging();
					this._P_PublishedDate = value;
					this.SendPropertyChanged("P_PublishedDate");
					this.OnP_PublishedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_AuthorName", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string P_AuthorName
		{
			get
			{
				return this._P_AuthorName;
			}
			set
			{
				if ((this._P_AuthorName != value))
				{
					this.OnP_AuthorNameChanging(value);
					this.SendPropertyChanging();
					this._P_AuthorName = value;
					this.SendPropertyChanged("P_AuthorName");
					this.OnP_AuthorNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_category", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string P_category
		{
			get
			{
				return this._P_category;
			}
			set
			{
				if ((this._P_category != value))
				{
					this.OnP_categoryChanging(value);
					this.SendPropertyChanging();
					this._P_category = value;
					this.SendPropertyChanged("P_category");
					this.OnP_categoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Language", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string P_Language
		{
			get
			{
				return this._P_Language;
			}
			set
			{
				if ((this._P_Language != value))
				{
					this.OnP_LanguageChanging(value);
					this.SendPropertyChanging();
					this._P_Language = value;
					this.SendPropertyChanged("P_Language");
					this.OnP_LanguageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[User]")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Username;
		
		private string _U_name;
		
		private string _U_surname;
		
		private System.Nullable<System.DateTime> _U_dob;
		
		private string _U_email;
		
		private string _U_password;
		
		private string _U_type;
		
		private int _U_active;
		
		private string _U_PointsValue;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnU_nameChanging(string value);
    partial void OnU_nameChanged();
    partial void OnU_surnameChanging(string value);
    partial void OnU_surnameChanged();
    partial void OnU_dobChanging(System.Nullable<System.DateTime> value);
    partial void OnU_dobChanged();
    partial void OnU_emailChanging(string value);
    partial void OnU_emailChanged();
    partial void OnU_passwordChanging(string value);
    partial void OnU_passwordChanged();
    partial void OnU_typeChanging(string value);
    partial void OnU_typeChanged();
    partial void OnU_activeChanging(int value);
    partial void OnU_activeChanged();
    partial void OnU_PointsValueChanging(string value);
    partial void OnU_PointsValueChanged();
    #endregion
		
		public User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string U_name
		{
			get
			{
				return this._U_name;
			}
			set
			{
				if ((this._U_name != value))
				{
					this.OnU_nameChanging(value);
					this.SendPropertyChanging();
					this._U_name = value;
					this.SendPropertyChanged("U_name");
					this.OnU_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_surname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string U_surname
		{
			get
			{
				return this._U_surname;
			}
			set
			{
				if ((this._U_surname != value))
				{
					this.OnU_surnameChanging(value);
					this.SendPropertyChanging();
					this._U_surname = value;
					this.SendPropertyChanged("U_surname");
					this.OnU_surnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_dob", DbType="Date")]
		public System.Nullable<System.DateTime> U_dob
		{
			get
			{
				return this._U_dob;
			}
			set
			{
				if ((this._U_dob != value))
				{
					this.OnU_dobChanging(value);
					this.SendPropertyChanging();
					this._U_dob = value;
					this.SendPropertyChanged("U_dob");
					this.OnU_dobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_email", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string U_email
		{
			get
			{
				return this._U_email;
			}
			set
			{
				if ((this._U_email != value))
				{
					this.OnU_emailChanging(value);
					this.SendPropertyChanging();
					this._U_email = value;
					this.SendPropertyChanged("U_email");
					this.OnU_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string U_password
		{
			get
			{
				return this._U_password;
			}
			set
			{
				if ((this._U_password != value))
				{
					this.OnU_passwordChanging(value);
					this.SendPropertyChanging();
					this._U_password = value;
					this.SendPropertyChanged("U_password");
					this.OnU_passwordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_type", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string U_type
		{
			get
			{
				return this._U_type;
			}
			set
			{
				if ((this._U_type != value))
				{
					this.OnU_typeChanging(value);
					this.SendPropertyChanging();
					this._U_type = value;
					this.SendPropertyChanged("U_type");
					this.OnU_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_active", DbType="Int NOT NULL")]
		public int U_active
		{
			get
			{
				return this._U_active;
			}
			set
			{
				if ((this._U_active != value))
				{
					this.OnU_activeChanging(value);
					this.SendPropertyChanging();
					this._U_active = value;
					this.SendPropertyChanged("U_active");
					this.OnU_activeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_U_PointsValue", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string U_PointsValue
		{
			get
			{
				return this._U_PointsValue;
			}
			set
			{
				if ((this._U_PointsValue != value))
				{
					this.OnU_PointsValueChanging(value);
					this.SendPropertyChanging();
					this._U_PointsValue = value;
					this.SendPropertyChanged("U_PointsValue");
					this.OnU_PointsValueChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SHOPPING_CART")]
	public partial class SHOPPING_CART : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _User_ID;
		
		private int _Product_ID;
		
		private int _Order_Quantity;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUser_IDChanging(int value);
    partial void OnUser_IDChanged();
    partial void OnProduct_IDChanging(int value);
    partial void OnProduct_IDChanged();
    partial void OnOrder_QuantityChanging(int value);
    partial void OnOrder_QuantityChanged();
    #endregion
		
		public SHOPPING_CART()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_ID", DbType="Int NOT NULL")]
		public int User_ID
		{
			get
			{
				return this._User_ID;
			}
			set
			{
				if ((this._User_ID != value))
				{
					this.OnUser_IDChanging(value);
					this.SendPropertyChanging();
					this._User_ID = value;
					this.SendPropertyChanged("User_ID");
					this.OnUser_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product_ID", DbType="Int NOT NULL")]
		public int Product_ID
		{
			get
			{
				return this._Product_ID;
			}
			set
			{
				if ((this._Product_ID != value))
				{
					this.OnProduct_IDChanging(value);
					this.SendPropertyChanging();
					this._Product_ID = value;
					this.SendPropertyChanged("Product_ID");
					this.OnProduct_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Order_Quantity", DbType="Int NOT NULL")]
		public int Order_Quantity
		{
			get
			{
				return this._Order_Quantity;
			}
			set
			{
				if ((this._Order_Quantity != value))
				{
					this.OnOrder_QuantityChanging(value);
					this.SendPropertyChanging();
					this._Order_Quantity = value;
					this.SendPropertyChanged("Order_Quantity");
					this.OnOrder_QuantityChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PurchaseInfo")]
	public partial class PurchaseInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private int _User_Id;
		
		private int _Invoice_Id;
		
		private string _ProductCost;
		
		private string _Order_ID;
		
		private string _ProductName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUser_IdChanging(int value);
    partial void OnUser_IdChanged();
    partial void OnInvoice_IdChanging(int value);
    partial void OnInvoice_IdChanged();
    partial void OnProductCostChanging(string value);
    partial void OnProductCostChanged();
    partial void OnOrder_IDChanging(string value);
    partial void OnOrder_IDChanged();
    partial void OnProductNameChanging(string value);
    partial void OnProductNameChanged();
    #endregion
		
		public PurchaseInfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Id", DbType="Int NOT NULL")]
		public int User_Id
		{
			get
			{
				return this._User_Id;
			}
			set
			{
				if ((this._User_Id != value))
				{
					this.OnUser_IdChanging(value);
					this.SendPropertyChanging();
					this._User_Id = value;
					this.SendPropertyChanged("User_Id");
					this.OnUser_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Invoice_Id", DbType="Int NOT NULL")]
		public int Invoice_Id
		{
			get
			{
				return this._Invoice_Id;
			}
			set
			{
				if ((this._Invoice_Id != value))
				{
					this.OnInvoice_IdChanging(value);
					this.SendPropertyChanging();
					this._Invoice_Id = value;
					this.SendPropertyChanged("Invoice_Id");
					this.OnInvoice_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductCost", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ProductCost
		{
			get
			{
				return this._ProductCost;
			}
			set
			{
				if ((this._ProductCost != value))
				{
					this.OnProductCostChanging(value);
					this.SendPropertyChanging();
					this._ProductCost = value;
					this.SendPropertyChanged("ProductCost");
					this.OnProductCostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Order_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Order_ID
		{
			get
			{
				return this._Order_ID;
			}
			set
			{
				if ((this._Order_ID != value))
				{
					this.OnOrder_IDChanging(value);
					this.SendPropertyChanging();
					this._Order_ID = value;
					this.SendPropertyChanged("Order_ID");
					this.OnOrder_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ProductName
		{
			get
			{
				return this._ProductName;
			}
			set
			{
				if ((this._ProductName != value))
				{
					this.OnProductNameChanging(value);
					this.SendPropertyChanging();
					this._ProductName = value;
					this.SendPropertyChanged("ProductName");
					this.OnProductNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
